### ISSUE TITLE
windows上tpm命令冲突了

### ISSUE THREAD

**Issue by zhaoyunyes** [fjc0k/tbify#4]
如图，会打开左边的窗口
![image](https://github.com/fjc0k/tbify/assets/16451550/6f15478c-af68-4be3-b5a6-ebecdbb8bf90)

**Comment by fjc0k** [comment]
已解决，升级到最新版即可。

**Comment by fjc0k** [comment]
<img width="953" alt="image" src="https://github.com/fjc0k/tbify/assets/13151189/01328a89-0dbc-4b4b-a121-b1749dda4620">
